apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istiod-remote-proxy-controller-istio-system
  labels:
    app: istiod
    release: istio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istiod-remote-proxy-controller-istio-system
subjects:
- kind: ServiceAccount
  name: istiod
  namespace: istio-system

