apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-cni
  namespace: istio-system
  labels:
    app: istio-cni
    release: istio
    istio.io/rev: default
    install.operator.istio.io/owning-resource: unknown
    operator.istio.io/component: "Cni"

