apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istiod-remote-proxy-controller-istio-system
  labels:
    app: istiod
    release: istio
rules:
- apiGroups: [""]
  verbs: [ "get", "watch", "list", "update", "patch", "create", "delete" ]
  resources: [ "pods"]
- apiGroups: [""]
  verbs: [ "get", "watch", "list" ]
  resources: [ "serviceaccounts"]

